### ISSUE TITLE
Which cryptonight variant?

### ISSUE THREAD

**Issue by Cryptonizor** [wkta/ReadableCryptoMiner#1]
Can you confirm which cryptonight variant this script works with?  Has it been updated for the upgrade Monero did to Cryptonight V8 on October 18th?

Awesome project!  Been looking for something like this in pure python!

**Comment by wkta** [comment]
it has been tested and works properly with "Cryptonight V7" (April 2018 hard fork).
"Cryptonight V8" and the more recent "CryptoNightR" (March 2019 hard fork) aren't supported ATM
I'll create a new issue for that
